with source_events as (
    select *
    from {{ source('growth_raw', 'bronze_events_union') }}
),

deduped as (
    select
        *,
        row_number() over (
            partition by event_id
            order by ingested_at desc, kafka_offset desc
        ) as duplicate_rank
    from source_events
)

select
    cast(event_id as string) as event_id,
    cast(event_type as string) as event_type,
    cast(event_timestamp as timestamp) as event_timestamp,
    cast(event_date as date) as event_date,
    cast(schema_version as int64) as schema_version,
    cast(advertiser_id as string) as advertiser_id,
    cast(product_id as string) as product_id,
    cast(campaign_id as string) as campaign_id,
    cast(ad_group_id as string) as ad_group_id,
    cast(creative_id as string) as creative_id,
    cast(objective as string) as objective,
    cast(channel as string) as channel,
    cast(device_id as string) as device_id,
    cast(user_id as string) as user_id,
    cast(session_id as string) as session_id,
    cast(audience_segment_id as string) as audience_segment_id,
    cast(targeting_tag_ids as string) as targeting_tag_ids,
    cast(country as string) as country,
    cast(region as string) as region,
    cast(city as string) as city,
    cast(device_type as string) as device_type,
    cast(platform as string) as platform,
    cast(ingest_source as string) as ingest_source,
    cast(impression_id as string) as impression_id,
    cast(placement as string) as placement,
    cast(bid_type as string) as bid_type,
    cast(cost_micros as int64) as cost_micros,
    cast(is_viewable as bool) as is_viewable,
    cast(view_id as string) as view_id,
    cast(watch_seconds as float64) as watch_seconds,
    cast(video_duration_seconds as int64) as video_duration_seconds,
    cast(view_percent as float64) as view_percent,
    cast(is_engaged_view as bool) as is_engaged_view,
    cast(click_id as string) as click_id,
    cast(destination_url as string) as destination_url,
    cast(click_type as string) as click_type,
    cast(engagement_id as string) as engagement_id,
    cast(engagement_type as string) as engagement_type,
    cast(content_id as string) as content_id,
    cast(is_key_engagement as bool) as is_key_engagement,
    cast(page_view_id as string) as page_view_id,
    cast(url as string) as url,
    cast(referrer as string) as referrer,
    cast(load_time_ms as int64) as load_time_ms,
    cast(install_id as string) as install_id,
    cast(app_version as string) as app_version,
    cast(os_version as string) as os_version,
    cast(attributed_click_id as string) as attributed_click_id,
    cast(install_source as string) as install_source,
    cast(signup_id as string) as signup_id,
    cast(signup_method as string) as signup_method,
    cast(marketing_opt_in as bool) as marketing_opt_in,
    cast(referral_code as string) as referral_code,
    cast(activation_id as string) as activation_id,
    cast(activation_event_name as string) as activation_event_name,
    cast(activation_value as float64) as activation_value,
    cast(hours_since_signup as float64) as hours_since_signup,
    cast(product_sku as string) as product_sku,
    cast(category as string) as category,
    cast(price as float64) as price,
    cast(cart_id as string) as cart_id,
    cast(quantity as int64) as quantity,
    cast(checkout_id as string) as checkout_id,
    cast(cart_value as float64) as cart_value,
    cast(purchase_id as string) as purchase_id,
    cast(conversion_id as string) as conversion_id,
    cast(order_id as string) as order_id,
    cast(purchase_type as string) as purchase_type,
    cast(revenue as float64) as revenue,
    cast(currency as string) as currency,
    cast(payment_method as string) as payment_method,
    cast(form_id as string) as form_id,
    cast(lead_type as string) as lead_type,
    cast(landing_page_id as string) as landing_page_id,
    cast(lead_id as string) as lead_id,
    cast(lead_value as float64) as lead_value,
    cast(qualification_score as float64) as qualification_score,
    cast(qualified_value as float64) as qualified_value,
    cast(qualified_at as timestamp) as qualified_at,
    cast(trial_id as string) as trial_id,
    cast(plan_id as string) as plan_id,
    cast(trial_length_days as int64) as trial_length_days,
    cast(subscription_id as string) as subscription_id,
    cast(billing_period as string) as billing_period,
    cast(renewal_number as int64) as renewal_number,
    cast(query as string) as search_query,
    cast(result_count as int64) as result_count,
    cast(booking_type as string) as booking_type,
    cast(cta_id as string) as cta_id,
    cast(cta_type as string) as cta_type,
    cast(business_location_id as string) as business_location_id,
    cast(offline_conversion_id as string) as offline_conversion_id,
    cast(conversion_type as string) as conversion_type,
    cast(match_confidence as float64) as match_confidence,
    cast(event_value as float64) as event_value,
    cast(event_properties as string) as event_properties,
    cast(kafka_topic as string) as kafka_topic,
    cast(kafka_partition as int64) as kafka_partition,
    cast(kafka_offset as int64) as kafka_offset,
    cast(raw_payload as string) as raw_payload,
    cast(ingested_at as timestamp) as ingested_at
from deduped
where duplicate_rank = 1
