from __future__ import annotations

from pyspark.sql.types import (
    BooleanType,
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)


COMMON_FIELDS = [
    StructField("event_id", StringType(), False),
    StructField("event_type", StringType(), False),
    StructField("event_timestamp", StringType(), False),
    StructField("event_date", StringType(), False),
    StructField("schema_version", IntegerType(), False),
    StructField("advertiser_id", StringType(), False),
    StructField("product_id", StringType(), False),
    StructField("campaign_id", StringType(), False),
    StructField("ad_group_id", StringType(), True),
    StructField("creative_id", StringType(), True),
    StructField("objective", StringType(), False),
    StructField("channel", StringType(), False),
    StructField("device_id", StringType(), False),
    StructField("user_id", StringType(), True),
    StructField("session_id", StringType(), True),
    StructField("audience_segment_id", StringType(), True),
    StructField("targeting_tag_ids", StringType(), True),
    StructField("country", StringType(), False),
    StructField("region", StringType(), True),
    StructField("city", StringType(), True),
    StructField("device_type", StringType(), False),
    StructField("platform", StringType(), False),
    StructField("ingest_source", StringType(), False),
]


EVENT_SPECIFIC_FIELDS = [
    StructField("impression_id", StringType(), True),
    StructField("placement", StringType(), True),
    StructField("bid_type", StringType(), True),
    StructField("cost_micros", LongType(), True),
    StructField("is_viewable", BooleanType(), True),
    StructField("view_id", StringType(), True),
    StructField("watch_seconds", DoubleType(), True),
    StructField("video_duration_seconds", IntegerType(), True),
    StructField("view_percent", DoubleType(), True),
    StructField("is_engaged_view", BooleanType(), True),
    StructField("click_id", StringType(), True),
    StructField("destination_url", StringType(), True),
    StructField("click_type", StringType(), True),
    StructField("engagement_id", StringType(), True),
    StructField("engagement_type", StringType(), True),
    StructField("content_id", StringType(), True),
    StructField("is_key_engagement", BooleanType(), True),
    StructField("page_view_id", StringType(), True),
    StructField("url", StringType(), True),
    StructField("referrer", StringType(), True),
    StructField("load_time_ms", IntegerType(), True),
    StructField("install_id", StringType(), True),
    StructField("app_version", StringType(), True),
    StructField("os_version", StringType(), True),
    StructField("attributed_click_id", StringType(), True),
    StructField("install_source", StringType(), True),
    StructField("signup_id", StringType(), True),
    StructField("signup_method", StringType(), True),
    StructField("marketing_opt_in", BooleanType(), True),
    StructField("referral_code", StringType(), True),
    StructField("activation_id", StringType(), True),
    StructField("activation_event_name", StringType(), True),
    StructField("activation_value", DoubleType(), True),
    StructField("hours_since_signup", DoubleType(), True),
    StructField("product_sku", StringType(), True),
    StructField("category", StringType(), True),
    StructField("price", DoubleType(), True),
    StructField("cart_id", StringType(), True),
    StructField("quantity", IntegerType(), True),
    StructField("checkout_id", StringType(), True),
    StructField("cart_value", DoubleType(), True),
    StructField("purchase_id", StringType(), True),
    StructField("conversion_id", StringType(), True),
    StructField("order_id", StringType(), True),
    StructField("purchase_type", StringType(), True),
    StructField("revenue", DoubleType(), True),
    StructField("currency", StringType(), True),
    StructField("payment_method", StringType(), True),
    StructField("form_id", StringType(), True),
    StructField("lead_type", StringType(), True),
    StructField("landing_page_id", StringType(), True),
    StructField("lead_id", StringType(), True),
    StructField("lead_value", DoubleType(), True),
    StructField("qualification_score", DoubleType(), True),
    StructField("qualified_value", DoubleType(), True),
    StructField("qualified_at", StringType(), True),
    StructField("trial_id", StringType(), True),
    StructField("plan_id", StringType(), True),
    StructField("trial_length_days", IntegerType(), True),
    StructField("subscription_id", StringType(), True),
    StructField("billing_period", StringType(), True),
    StructField("renewal_number", IntegerType(), True),
    StructField("query", StringType(), True),
    StructField("result_count", IntegerType(), True),
    StructField("booking_type", StringType(), True),
    StructField("cta_id", StringType(), True),
    StructField("cta_type", StringType(), True),
    StructField("business_location_id", StringType(), True),
    StructField("offline_conversion_id", StringType(), True),
    StructField("conversion_type", StringType(), True),
    StructField("match_confidence", DoubleType(), True),
    StructField("event_value", DoubleType(), True),
]


EVENT_SCHEMA = StructType(COMMON_FIELDS + EVENT_SPECIFIC_FIELDS)


TOPIC_TABLES = {
    "ad_impressions": "bronze_ad_impressions",
    "video_views": "bronze_video_views",
    "ad_clicks": "bronze_ad_clicks",
    "engagements": "bronze_engagements",
    "landing_page_views": "bronze_landing_page_views",
    "app_installs": "bronze_app_installs",
    "signups": "bronze_signups",
    "activations": "bronze_activations",
    "commerce_events": "bronze_commerce_events",
    "lead_events": "bronze_lead_events",
    "subscription_events": "bronze_subscription_events",
    "marketplace_events": "bronze_marketplace_events",
    "offline_conversions": "bronze_offline_conversions",
}

TOPICS = tuple(TOPIC_TABLES)
